apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  capacity:
    storage: 1Gi        # 1GB disk sahəsi
  accessModes:
    - ReadWriteOnce     # yalnız bir Pod yaza bilər
  hostPath:
    path: /data/redis   # Ubuntu-da bu qovluğa saxla

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi      # 1GB istəyirəm
