name: MiniLink CI/CD

on:
  push:
    branches:
      - main        # main branch-ə push olduqda işlə

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu çək
      uses: actions/checkout@v3

    - name: Python qur
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Asılılıqları qur
      run: |
        pip install flask redis

    - name: Test et
      run: |
        echo "Testlər keçdi ✅"

    - name: Deploy oldu
      run: |
        echo "🚀 MiniLink deploy oldu!"
